### PR TITLE
Login fragment

### PR DESCRIPTION
**Pull request by jharshman**
# Summary Of Changes
1. Facebook integration ( Application ID, Libraries, etc... )
2. Introduce "Log in With Facebook" functionality
3. Introduce basic fragment layout and management for content_main and MainActivity
4. ViewPager Fragment Implementation
5. Login page fragment
6. Additional app tutorial fragments
7. ViewPager fragment transition animation ( Zoom Out and Slide )

These changes to our clean master branch should give us a basic starting point on which we can start building the rest of our application upon.  The hope is that with the exception of a few tasks, most of what we need to get done can be accomplished in fragments, hence the reason why I designed the login as a fragment within a view pager fragment, instead of an activity.

### CODE REVIEW

**Comment by jharshman** [comment]
Will not be merged until everyone reviews and gives their LGTM.

**Comment by dmacy5** [comment]
Eveything looks good to me.

**Comment by dmacy5** [comment]
Looks good to me

**Comment by jharshman** [comment]
Everyone has given their LGTM.
Squashing commits and merging.

**Pull request merged**
